
logging:
  level:
    org.hibernate.type: trace
    org.springframework.web.client: DEBUG
    httpclient.wire: DEBUG

server:
  tomcat:
    relaxed-query-chars: <, >, [, \, ], ^, `, {, |, }

spring:
  application:
    name: alone-auth
  profiles:
    include:
    - app
    - oauth2
  h2:
    console:
      enabled: true
#    datasource:
#        url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#        username: root
#        password: callicoder

  jpa:
    show-sql: true
#        hibernate:
#            ddl-auto: update
#            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect